### ISSUE TITLE
topBar 컴포넌트 구현

### ISSUE THREAD

**Issue by hjsong333** [masters2023-4th-project-carrot-talk/carrot-talk-fe#12]
## Feature 

여러 페이지에서 사용되는 topBar 컴포넌트 구현

## Tasks
- [x] 사용처 파악
- [x] 레이아웃
- [x] 동작 시나리오 작성
- [x] 상태, 렌더링 결과
- [x] 페이지별 헤더 작성

## 기타
- 사용 환경에 따라서 **제목**과 **형태**가 변한다.
  - 페이지 이동을 하지 않는 카테고리, 내 물건 팔기, 상품 상세 페이지, 채팅 상세 페이지에서도 사용된다.
  - 구성 요소가 사용처마다 다르다.
  - 배경색상과 외곽선이 다른 스타일도 있다.
- 좌우 버튼의 동작을 위해 상태관리가 필요하다.
  - topBar 좌우 버튼의 동작이 컴포넌트마다 제각각이므로 topBar는 각 컴포넌트에서 렌더링하여 관리하는 것이 바람직해보임.

**Comment by hjsong333** [comment]
헤더 레이아웃 참고 자료
https://www.daleseo.com/css-position-sticky-header/

**Comment by hjsong333** [comment]
Home 헤더 작성 중 Dropdown의 backdrop(dim) 영역이 헤더로 제한되는 문제
