### ISSUE TITLE
상세페이지 기능 구현

### ISSUE THREAD

**Issue by gunoc** [masters2023-4th-project-carrot-talk/carrot-talk-fe#38]
## Tasks
- [ ] 상세페이지 기능구현을 합니다
- [ ] 메인페이지의 alert창 중복으로 뜨는 문제 해결
- [ ] useProducts등 useProductsQuery로 네이밍 변경

## 기타

<-- 기타 사항을 적어주세요 -->
