### ISSUE TITLE
상세 페이지, 목록 페이지 리뷰 피드백 반영

### ISSUE THREAD

**Issue by gunoc** [masters2023-4th-project-carrot-talk/carrot-talk-fe#43]
## Tasks
- [x] 가격 0 원일때 '가격 없음' 표시
- [x] listitem 상태변경 드롭다운 객체 수정
- [x] product list에 호버시 ui변경
  - [x] 잠시 li title text 굵기 변화로
- [x] home 스크롤 보여주기
- [ ] home 스크롤 행동 수정
- [x] home product 리페치 제거
- [ ] 연동 확인
  - [ ] a팀 
    - [ ] 좋아요 상태 수정  x 
    - [ ] 비로그인시 상세페이지 안들어가짐
  - [ ] b팀 서버 유무 모름
- [x] status badge색상 수정
- [x] category 선택 유무 표시
- [x] 상품상태 dropdown에 기존 상태 표시(selected)
## 기타

<-- 기타 사항을 적어주세요 -->
